### ISSUE TITLE
Mage: The Ascension Revised Edition

### ISSUE THREAD

**Issue by jason-kerney** [ChainsawXIV/DST#20]
Hey,

First, I like your sheets. Your Mage: The Ascension 20th anniversary sheet is very awesome.

I have 2 small requests for this sheet.  The first, is can you also submit it under the "World of Darkness" system?

Second, would it be possible to get a version of the sheet that matched the Abilities and naming on the Revised Edition Sheet?

As for the  second request, I am willing to fork your work, make the changes, and submit a pull request.

Thank you for making awesome sheets.

**Comment by ChainsawXIV** [comment]
Glad you like it - I can definitely add a World of Darkness version.

If you'd like to create a version for Revised Edition, I'll gladly add it - just make sure you name the folder so it matches the slug of the DST, and it should be all good.

**Comment by jason-kerney** [comment]
Thanks!

**Comment by ChainsawXIV** [comment]
Mage sheet has been cloned to WOD.
